package sgfanalyst::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'sgfanalyst::Schema',

    connect_info => {
        dsn => 'dbi:SQLite:sgfanalyst.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

sgfanalyst::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<sgfanalyst>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<sgfanalyst::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.63

=head1 AUTHOR

Wes Caldwell

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
